version: "3"

services:
  base: &base
    hostname: drone-swarm-search
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
